
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CherkashinProject.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Tovares
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tovares()
    {

        this.GetTovara = new HashSet<GetTovara>();

        this.PostTovara = new HashSet<PostTovara>();

    }


    public int TovarId { get; set; }

    public string TovarName { get; set; }

    public int TovarArticle { get; set; }

    public int Count { get; set; }

    public int ColorId { get; set; }

    public int TovarCountryId { get; set; }



    public virtual Country Country { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GetTovara> GetTovara { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PostTovara> PostTovara { get; set; }

    public virtual TovarColor TovarColor { get; set; }

}

}
