//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CherkashinProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CherkashinProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ActionApply {
            get {
                return ResourceManager.GetString("ActionApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ActionLogin {
            get {
                return ResourceManager.GetString("ActionLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All product.
        /// </summary>
        public static string AllTovar {
            get {
                return ResourceManager.GetString("AllTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add prihodnaya.
        /// </summary>
        public static string BtnAddPrihodnaya {
            get {
                return ResourceManager.GetString("BtnAddPrihodnaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rashodnaya.
        /// </summary>
        public static string BtnAddRashodnaya {
            get {
                return ResourceManager.GetString("BtnAddRashodnaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tovar.
        /// </summary>
        public static string BtnAddTovar {
            get {
                return ResourceManager.GetString("BtnAddTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string BtnAddUser {
            get {
                return ResourceManager.GetString("BtnAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihodnaya.
        /// </summary>
        public static string BtnPrihodnaya {
            get {
                return ResourceManager.GetString("BtnPrihodnaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rashodnaya.
        /// </summary>
        public static string BtnRashodnaya {
            get {
                return ResourceManager.GetString("BtnRashodnaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully!.
        /// </summary>
        public static string CaptionSuccessfully {
            get {
                return ResourceManager.GetString("CaptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add color.
        /// </summary>
        public static string CBxAddColor {
            get {
                return ResourceManager.GetString("CBxAddColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add country.
        /// </summary>
        public static string CBxAddCountry {
            get {
                return ResourceManager.GetString("CBxAddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Kontragent.
        /// </summary>
        public static string CBxAddKontragent {
            get {
                return ResourceManager.GetString("CBxAddKontragent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role.
        /// </summary>
        public static string CBxAddRole {
            get {
                return ResourceManager.GetString("CBxAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sklad.
        /// </summary>
        public static string CBxAddSklad {
            get {
                return ResourceManager.GetString("CBxAddSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tovar.
        /// </summary>
        public static string CBxAddTovar {
            get {
                return ResourceManager.GetString("CBxAddTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string CBxAddUser {
            get {
                return ResourceManager.GetString("CBxAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string DGCount {
            get {
                return ResourceManager.GetString("DGCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of get.
        /// </summary>
        public static string DGDateOfGet {
            get {
                return ResourceManager.GetString("DGDateOfGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of sale.
        /// </summary>
        public static string DGDateOfSale {
            get {
                return ResourceManager.GetString("DGDateOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ID.
        /// </summary>
        public static string DGGetId {
            get {
                return ResourceManager.GetString("DGGetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontragent.
        /// </summary>
        public static string DGKontragent {
            get {
                return ResourceManager.GetString("DGKontragent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string DGManager {
            get {
                return ResourceManager.GetString("DGManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post ID.
        /// </summary>
        public static string DGPostId {
            get {
                return ResourceManager.GetString("DGPostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string DGPrice {
            get {
                return ResourceManager.GetString("DGPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad.
        /// </summary>
        public static string DGSklad {
            get {
                return ResourceManager.GetString("DGSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovar.
        /// </summary>
        public static string DGTovar {
            get {
                return ResourceManager.GetString("DGTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color duplicates!.
        /// </summary>
        public static string ErrorAddColorDuplicates {
            get {
                return ResourceManager.GetString("ErrorAddColorDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color cannot be empty!.
        /// </summary>
        public static string ErrorAddColorEmpty {
            get {
                return ResourceManager.GetString("ErrorAddColorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country duplicates!.
        /// </summary>
        public static string ErrorAddCountryDuplicates {
            get {
                return ResourceManager.GetString("ErrorAddCountryDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country cannot be empty!.
        /// </summary>
        public static string ErrorAddCountryEmpty {
            get {
                return ResourceManager.GetString("ErrorAddCountryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontragent duplicates!.
        /// </summary>
        public static string ErrorAddKontragentDuplicates {
            get {
                return ResourceManager.GetString("ErrorAddKontragentDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontragent cannot be empty!.
        /// </summary>
        public static string ErrorAddKontragentEmpty {
            get {
                return ResourceManager.GetString("ErrorAddKontragentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role duplicates!.
        /// </summary>
        public static string ErrorAddRoleDuplicates {
            get {
                return ResourceManager.GetString("ErrorAddRoleDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be empty!.
        /// </summary>
        public static string ErrorAddRoleEmpty {
            get {
                return ResourceManager.GetString("ErrorAddRoleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad duplicates!.
        /// </summary>
        public static string ErrorAddSkladDuplicates {
            get {
                return ResourceManager.GetString("ErrorAddSkladDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad cannot be empty!.
        /// </summary>
        public static string ErrorAddSkladEmpty {
            get {
                return ResourceManager.GetString("ErrorAddSkladEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Article&quot; have wrong format!.
        /// </summary>
        public static string ErrorArcticleFormat {
            get {
                return ResourceManager.GetString("ErrorArcticleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Article&quot; is empty!.
        /// </summary>
        public static string ErrorArticleEmpty {
            get {
                return ResourceManager.GetString("ErrorArticleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Color&quot; have wrong format!.
        /// </summary>
        public static string ErrorColor {
            get {
                return ResourceManager.GetString("ErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Count&quot; is empty!.
        /// </summary>
        public static string ErrorCountEmpty {
            get {
                return ResourceManager.GetString("ErrorCountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Count&quot; have wrong format!.
        /// </summary>
        public static string ErrorCountFormat {
            get {
                return ResourceManager.GetString("ErrorCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Country&quot; have wrong format!.
        /// </summary>
        public static string ErrorCountry {
            get {
                return ResourceManager.GetString("ErrorCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Kontragent&quot; have wrong format!.
        /// </summary>
        public static string ErrorKontragent {
            get {
                return ResourceManager.GetString("ErrorKontragent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Login&quot; is empty!.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Manager&quot; have wrong format!.
        /// </summary>
        public static string ErrorManager {
            get {
                return ResourceManager.GetString("ErrorManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Name&quot; is empty!.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Password&quot; is empty!.
        /// </summary>
        public static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Price&quot; is empty!.
        /// </summary>
        public static string ErrorPriceEmpty {
            get {
                return ResourceManager.GetString("ErrorPriceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Price&quot; have wrong format!.
        /// </summary>
        public static string ErrorPriceFormat {
            get {
                return ResourceManager.GetString("ErrorPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Role&quot; have wrong format!.
        /// </summary>
        public static string ErrorRole {
            get {
                return ResourceManager.GetString("ErrorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Sklad&quot; have wrong format!.
        /// </summary>
        public static string ErrorSklad {
            get {
                return ResourceManager.GetString("ErrorSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered something wrong!.
        /// </summary>
        public static string ErrorSomethingWrong {
            get {
                return ResourceManager.GetString("ErrorSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Tovar&quot; have wrong format!.
        /// </summary>
        public static string ErrorTovar {
            get {
                return ResourceManager.GetString("ErrorTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock there is no necessary quantity of goods!.
        /// </summary>
        public static string ErrorTovarCount {
            get {
                return ResourceManager.GetString("ErrorTovarCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Tovar name&quot; is empty!.
        /// </summary>
        public static string ErrorTovarName {
            get {
                return ResourceManager.GetString("ErrorTovarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error!.
        /// </summary>
        public static string ErrorUnspecified {
            get {
                return ResourceManager.GetString("ErrorUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by tovar :.
        /// </summary>
        public static string FilterByTovar {
            get {
                return ResourceManager.GetString("FilterByTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added!.
        /// </summary>
        public static string MessageSuccessfullAdd {
            get {
                return ResourceManager.GetString("MessageSuccessfullAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited!.
        /// </summary>
        public static string MessageSuccessfullEdit {
            get {
                return ResourceManager.GetString("MessageSuccessfullEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number product.
        /// </summary>
        public static string NumberTovar {
            get {
                return ResourceManager.GetString("NumberTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string ProductArticle {
            get {
                return ResourceManager.GetString("ProductArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ProductColor {
            get {
                return ResourceManager.GetString("ProductColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ProductCounrty {
            get {
                return ResourceManager.GetString("ProductCounrty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by sklad or manger :.
        /// </summary>
        public static string SearchBySkladOrManager {
            get {
                return ResourceManager.GetString("SearchBySkladOrManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article :.
        /// </summary>
        public static string TextArticle {
            get {
                return ResourceManager.GetString("TextArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color :.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count :.
        /// </summary>
        public static string TextCount {
            get {
                return ResourceManager.GetString("TextCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        public static string TextCountry {
            get {
                return ResourceManager.GetString("TextCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of get :.
        /// </summary>
        public static string TextDateOfGet {
            get {
                return ResourceManager.GetString("TextDateOfGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of sale :.
        /// </summary>
        public static string TextDateOfSale {
            get {
                return ResourceManager.GetString("TextDateOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by country :.
        /// </summary>
        public static string TextFilterByCountry {
            get {
                return ResourceManager.GetString("TextFilterByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by role :.
        /// </summary>
        public static string TextFilterByRole {
            get {
                return ResourceManager.GetString("TextFilterByRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by tovar :.
        /// </summary>
        public static string TextFilterByTovar {
            get {
                return ResourceManager.GetString("TextFilterByTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontragent :.
        /// </summary>
        public static string TextKontragent {
            get {
                return ResourceManager.GetString("TextKontragent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choouse the launguage:.
        /// </summary>
        public static string TextLang {
            get {
                return ResourceManager.GetString("TextLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string TextLogin {
            get {
                return ResourceManager.GetString("TextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager :.
        /// </summary>
        public static string TextManager {
            get {
                return ResourceManager.GetString("TextManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string TextPassword {
            get {
                return ResourceManager.GetString("TextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        public static string TextPrice {
            get {
                return ResourceManager.GetString("TextPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string TextQt {
            get {
                return ResourceManager.GetString("TextQt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role :.
        /// </summary>
        public static string TextRole {
            get {
                return ResourceManager.GetString("TextRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by manager or kontragent :.
        /// </summary>
        public static string TextSearchByKontragentOrManager {
            get {
                return ResourceManager.GetString("TextSearchByKontragentOrManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by manager or sklad :.
        /// </summary>
        public static string TextSearchByManagerOrSkladName {
            get {
                return ResourceManager.GetString("TextSearchByManagerOrSkladName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name :.
        /// </summary>
        public static string TextSearchByName {
            get {
                return ResourceManager.GetString("TextSearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by product name :.
        /// </summary>
        public static string TextSearchByProductName {
            get {
                return ResourceManager.GetString("TextSearchByProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string TextSelect {
            get {
                return ResourceManager.GetString("TextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller :.
        /// </summary>
        public static string TextSeller {
            get {
                return ResourceManager.GetString("TextSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad :.
        /// </summary>
        public static string TextSklad {
            get {
                return ResourceManager.GetString("TextSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovar :.
        /// </summary>
        public static string TextTovar {
            get {
                return ResourceManager.GetString("TextTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovar name :.
        /// </summary>
        public static string TextTovarName {
            get {
                return ResourceManager.GetString("TextTovarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string UsersId {
            get {
                return ResourceManager.GetString("UsersId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UsersLogin {
            get {
                return ResourceManager.GetString("UsersLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered the wrong password.
        /// </summary>
        public static string WrongPass {
            get {
                return ResourceManager.GetString("WrongPass", resourceCulture);
            }
        }
    }
}
