//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CherkashinProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CherkashinProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ActionApply {
            get {
                return ResourceManager.GetString("ActionApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ActionLogin {
            get {
                return ResourceManager.GetString("ActionLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All product.
        /// </summary>
        public static string AllTovar {
            get {
                return ResourceManager.GetString("AllTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihodnaya.
        /// </summary>
        public static string BtnPrihodnaya {
            get {
                return ResourceManager.GetString("BtnPrihodnaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rashodnaya.
        /// </summary>
        public static string BtnRashodnaya {
            get {
                return ResourceManager.GetString("BtnRashodnaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add color.
        /// </summary>
        public static string CBxAddColor {
            get {
                return ResourceManager.GetString("CBxAddColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add country.
        /// </summary>
        public static string CBxAddCountry {
            get {
                return ResourceManager.GetString("CBxAddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string DGCount {
            get {
                return ResourceManager.GetString("DGCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of get.
        /// </summary>
        public static string DGDateOfGet {
            get {
                return ResourceManager.GetString("DGDateOfGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of sale.
        /// </summary>
        public static string DGDateOfSale {
            get {
                return ResourceManager.GetString("DGDateOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ID.
        /// </summary>
        public static string DGGetId {
            get {
                return ResourceManager.GetString("DGGetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontragent.
        /// </summary>
        public static string DGKontragent {
            get {
                return ResourceManager.GetString("DGKontragent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string DGManager {
            get {
                return ResourceManager.GetString("DGManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string DGPrice {
            get {
                return ResourceManager.GetString("DGPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad.
        /// </summary>
        public static string DGSklad {
            get {
                return ResourceManager.GetString("DGSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovar.
        /// </summary>
        public static string DGTovar {
            get {
                return ResourceManager.GetString("DGTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color duplicates!.
        /// </summary>
        public static string ErrorAddColorDuplicates {
            get {
                return ResourceManager.GetString("ErrorAddColorDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color cannot be empty!.
        /// </summary>
        public static string ErrorAddColorEmpty {
            get {
                return ResourceManager.GetString("ErrorAddColorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country duplicates!.
        /// </summary>
        public static string ErrorAddCountryDuplicates {
            get {
                return ResourceManager.GetString("ErrorAddCountryDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country cannot be empty!.
        /// </summary>
        public static string ErrorAddCountryEmpty {
            get {
                return ResourceManager.GetString("ErrorAddCountryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered something wrong!.
        /// </summary>
        public static string ErrorSomethingWrong {
            get {
                return ResourceManager.GetString("ErrorSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error!.
        /// </summary>
        public static string ErrorUnspecified {
            get {
                return ResourceManager.GetString("ErrorUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by tovar :.
        /// </summary>
        public static string FilterByTovar {
            get {
                return ResourceManager.GetString("FilterByTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added!.
        /// </summary>
        public static string MessageSuccessfullAdd {
            get {
                return ResourceManager.GetString("MessageSuccessfullAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited!.
        /// </summary>
        public static string MessageSuccessfullEdit {
            get {
                return ResourceManager.GetString("MessageSuccessfullEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number product.
        /// </summary>
        public static string NumberTovar {
            get {
                return ResourceManager.GetString("NumberTovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string ProductArticle {
            get {
                return ResourceManager.GetString("ProductArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ProductColor {
            get {
                return ResourceManager.GetString("ProductColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ProductCounrty {
            get {
                return ResourceManager.GetString("ProductCounrty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by sklad or manger :.
        /// </summary>
        public static string SearchBySkladOrManager {
            get {
                return ResourceManager.GetString("SearchBySkladOrManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article :.
        /// </summary>
        public static string TextArticle {
            get {
                return ResourceManager.GetString("TextArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color :.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count :.
        /// </summary>
        public static string TextCount {
            get {
                return ResourceManager.GetString("TextCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        public static string TextCountry {
            get {
                return ResourceManager.GetString("TextCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by country :.
        /// </summary>
        public static string TextFilterByCountry {
            get {
                return ResourceManager.GetString("TextFilterByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by role :.
        /// </summary>
        public static string TextFilterByRole {
            get {
                return ResourceManager.GetString("TextFilterByRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choouse the launguage:.
        /// </summary>
        public static string TextLang {
            get {
                return ResourceManager.GetString("TextLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string TextLogin {
            get {
                return ResourceManager.GetString("TextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string TextPassword {
            get {
                return ResourceManager.GetString("TextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string TextQt {
            get {
                return ResourceManager.GetString("TextQt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name :.
        /// </summary>
        public static string TextSearchByName {
            get {
                return ResourceManager.GetString("TextSearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by product name :.
        /// </summary>
        public static string TextSearchByProductName {
            get {
                return ResourceManager.GetString("TextSearchByProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string TextSelect {
            get {
                return ResourceManager.GetString("TextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovar name :.
        /// </summary>
        public static string TextTovarName {
            get {
                return ResourceManager.GetString("TextTovarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string UsersId {
            get {
                return ResourceManager.GetString("UsersId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UsersLogin {
            get {
                return ResourceManager.GetString("UsersLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered the wrong password.
        /// </summary>
        public static string WrongPass {
            get {
                return ResourceManager.GetString("WrongPass", resourceCulture);
            }
        }
    }
}
